/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapabilityManifest } from './CapabilityManifest';
import {
    CapabilityManifestFromJSON,
    CapabilityManifestFromJSONTyped,
    CapabilityManifestToJSON,
    CapabilityManifestToJSONTyped,
} from './CapabilityManifest';

/**
 * 
 * @export
 * @interface AuthorizedManifest
 */
export interface AuthorizedManifest {
    /**
     * 
     * @type {string}
     * @memberof AuthorizedManifest
     */
    name: string;
    /**
     * 
     * @type {CapabilityManifest}
     * @memberof AuthorizedManifest
     */
    manifest: CapabilityManifest;
    /**
     * 
     * @type {Array<number>}
     * @memberof AuthorizedManifest
     */
    ownerSignature: Array<number>;
}

/**
 * Check if a given object implements the AuthorizedManifest interface.
 */
export function instanceOfAuthorizedManifest(value: object): value is AuthorizedManifest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('manifest' in value) || value['manifest'] === undefined) return false;
    if ((!('ownerSignature' in value) && !('owner_signature' in value)) || (value['ownerSignature'] === undefined && value['owner_signature'] === undefined)) return false;
    return true;
}

export function AuthorizedManifestFromJSON(json: any): AuthorizedManifest {
    return AuthorizedManifestFromJSONTyped(json, false);
}

export function AuthorizedManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizedManifest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'manifest': CapabilityManifestFromJSON(json['manifest']),
        'ownerSignature': json['owner_signature'],
    };
}

export function AuthorizedManifestToJSON(json: any): AuthorizedManifest {
    return AuthorizedManifestToJSONTyped(json, false);
}

export function AuthorizedManifestToJSONTyped(value?: AuthorizedManifest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'manifest': CapabilityManifestToJSON(value['manifest']),
        'owner_signature': value['ownerSignature'],
    };
}

