/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CapabilityManifest
 */
export interface CapabilityManifest {
    /**
     * 
     * @type {string}
     * @memberof CapabilityManifest
     */
    docType: string;
    /**
     * 
     * @type {string}
     * @memberof CapabilityManifest
     */
    kid: string;
    /**
     * 
     * @type {number}
     * @memberof CapabilityManifest
     */
    version: number;
    /**
     * 
     * @type {number}
     * @memberof CapabilityManifest
     */
    validFrom: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof CapabilityManifest
     */
    services: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof CapabilityManifest
     */
    signature?: string | null;
}

/**
 * Check if a given object implements the CapabilityManifest interface.
 */
export function instanceOfCapabilityManifest(value: object): value is CapabilityManifest {
    if ((!('docType' in value) && !('doc_type' in value)) || (value['docType'] === undefined && value['doc_type'] === undefined)) return false;
    if (!('kid' in value) || value['kid'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('validFrom' in value) && !('valid_from' in value)) || (value['validFrom'] === undefined && value['valid_from'] === undefined)) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function CapabilityManifestFromJSON(json: any): CapabilityManifest {
    return CapabilityManifestFromJSONTyped(json, false);
}

export function CapabilityManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilityManifest {
    if (json == null) {
        return json;
    }
    return {
        
        'docType': json['doc_type'],
        'kid': json['kid'],
        'version': json['version'],
        'validFrom': json['valid_from'],
        'services': json['services'],
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function CapabilityManifestToJSON(json: any): CapabilityManifest {
    return CapabilityManifestToJSONTyped(json, false);
}

export function CapabilityManifestToJSONTyped(value?: CapabilityManifest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'doc_type': value['docType'],
        'kid': value['kid'],
        'version': value['version'],
        'valid_from': value['validFrom'],
        'services': value['services'],
        'signature': value['signature'],
    };
}

