/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Commitment
 */
export interface Commitment {
    /**
     * 
     * @type {Array<number>}
     * @memberof Commitment
     */
    hash: Array<number>;
}

/**
 * Check if a given object implements the Commitment interface.
 */
export function instanceOfCommitment(value: object): value is Commitment {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function CommitmentFromJSON(json: any): Commitment {
    return CommitmentFromJSONTyped(json, false);
}

export function CommitmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Commitment {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
    };
}

export function CommitmentToJSON(json: any): Commitment {
    return CommitmentToJSONTyped(json, false);
}

export function CommitmentToJSONTyped(value?: Commitment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
    };
}

