/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteVdfTask200Response
 */
export interface DeleteVdfTask200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteVdfTask200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the DeleteVdfTask200Response interface.
 */
export function instanceOfDeleteVdfTask200Response(value: object): value is DeleteVdfTask200Response {
    return true;
}

export function DeleteVdfTask200ResponseFromJSON(json: any): DeleteVdfTask200Response {
    return DeleteVdfTask200ResponseFromJSONTyped(json, false);
}

export function DeleteVdfTask200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteVdfTask200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function DeleteVdfTask200ResponseToJSON(json: any): DeleteVdfTask200Response {
    return DeleteVdfTask200ResponseToJSONTyped(json, false);
}

export function DeleteVdfTask200ResponseToJSONTyped(value?: DeleteVdfTask200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

