/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VdfProof } from './VdfProof';
import {
    VdfProofFromJSON,
    VdfProofFromJSONTyped,
    VdfProofToJSON,
    VdfProofToJSONTyped,
} from './VdfProof';

/**
 * 
 * @export
 * @interface PreviousProof
 */
export interface PreviousProof {
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviousProof
     */
    salt: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof PreviousProof
     */
    drandPulse: number;
    /**
     * 
     * @type {string}
     * @memberof PreviousProof
     */
    drandRandomness: string;
    /**
     * 
     * @type {number}
     * @memberof PreviousProof
     */
    iterations: number;
    /**
     * 
     * @type {VdfProof}
     * @memberof PreviousProof
     */
    vdfProof: VdfProof;
    /**
     * 
     * @type {Array<number>}
     * @memberof PreviousProof
     */
    signature: Array<number>;
}

/**
 * Check if a given object implements the PreviousProof interface.
 */
export function instanceOfPreviousProof(value: object): value is PreviousProof {
    if (!('salt' in value) || value['salt'] === undefined) return false;
    if ((!('drandPulse' in value) && !('drand_pulse' in value)) || (value['drandPulse'] === undefined && value['drand_pulse'] === undefined)) return false;
    if ((!('drandRandomness' in value) && !('drand_randomness' in value)) || (value['drandRandomness'] === undefined && value['drand_randomness'] === undefined)) return false;
    if (!('iterations' in value) || value['iterations'] === undefined) return false;
    if ((!('vdfProof' in value) && !('vdf_proof' in value)) || (value['vdfProof'] === undefined && value['vdf_proof'] === undefined)) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function PreviousProofFromJSON(json: any): PreviousProof {
    return PreviousProofFromJSONTyped(json, false);
}

export function PreviousProofFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviousProof {
    if (json == null) {
        return json;
    }
    return {
        
        'salt': json['salt'],
        'drandPulse': json['drand_pulse'],
        'drandRandomness': json['drand_randomness'],
        'iterations': json['iterations'],
        'vdfProof': VdfProofFromJSON(json['vdf_proof']),
        'signature': json['signature'],
    };
}

export function PreviousProofToJSON(json: any): PreviousProof {
    return PreviousProofToJSONTyped(json, false);
}

export function PreviousProofToJSONTyped(value?: PreviousProof | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'salt': value['salt'],
        'drand_pulse': value['drandPulse'],
        'drand_randomness': value['drandRandomness'],
        'iterations': value['iterations'],
        'vdf_proof': VdfProofToJSON(value['vdfProof']),
        'signature': value['signature'],
    };
}

