/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reveal } from './Reveal';
import {
    RevealFromJSON,
    RevealFromJSONTyped,
    RevealToJSON,
    RevealToJSONTyped,
} from './Reveal';

/**
 * 
 * @export
 * @interface PublishRequest
 */
export interface PublishRequest {
    /**
     * 
     * @type {Reveal}
     * @memberof PublishRequest
     */
    reveal: Reveal;
}

/**
 * Check if a given object implements the PublishRequest interface.
 */
export function instanceOfPublishRequest(value: object): value is PublishRequest {
    if (!('reveal' in value) || value['reveal'] === undefined) return false;
    return true;
}

export function PublishRequestFromJSON(json: any): PublishRequest {
    return PublishRequestFromJSONTyped(json, false);
}

export function PublishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reveal': RevealFromJSON(json['reveal']),
    };
}

export function PublishRequestToJSON(json: any): PublishRequest {
    return PublishRequestToJSONTyped(json, false);
}

export function PublishRequestToJSONTyped(value?: PublishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reveal': RevealToJSON(value['reveal']),
    };
}

