/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishResponse
 */
export interface PublishResponse {
    /**
     * 
     * @type {string}
     * @memberof PublishResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PublishResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PublishResponse interface.
 */
export function instanceOfPublishResponse(value: object): value is PublishResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PublishResponseFromJSON(json: any): PublishResponse {
    return PublishResponseFromJSONTyped(json, false);
}

export function PublishResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
    };
}

export function PublishResponseToJSON(json: any): PublishResponse {
    return PublishResponseToJSONTyped(json, false);
}

export function PublishResponseToJSONTyped(value?: PublishResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

