/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapabilityManifest } from './CapabilityManifest';
import {
    CapabilityManifestFromJSON,
    CapabilityManifestFromJSONTyped,
    CapabilityManifestToJSON,
    CapabilityManifestToJSONTyped,
} from './CapabilityManifest';
import type { KidDocument } from './KidDocument';
import {
    KidDocumentFromJSON,
    KidDocumentFromJSONTyped,
    KidDocumentToJSON,
    KidDocumentToJSONTyped,
} from './KidDocument';

/**
 * 
 * @export
 * @interface ResolveKid200Response
 */
export interface ResolveKid200Response {
    /**
     * 
     * @type {KidDocument}
     * @memberof ResolveKid200Response
     */
    kidDocument?: KidDocument;
    /**
     * 
     * @type {CapabilityManifest}
     * @memberof ResolveKid200Response
     */
    manifestDocument?: CapabilityManifest;
}

/**
 * Check if a given object implements the ResolveKid200Response interface.
 */
export function instanceOfResolveKid200Response(value: object): value is ResolveKid200Response {
    return true;
}

export function ResolveKid200ResponseFromJSON(json: any): ResolveKid200Response {
    return ResolveKid200ResponseFromJSONTyped(json, false);
}

export function ResolveKid200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveKid200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'kidDocument': json['kid_document'] == null ? undefined : KidDocumentFromJSON(json['kid_document']),
        'manifestDocument': json['manifest_document'] == null ? undefined : CapabilityManifestFromJSON(json['manifest_document']),
    };
}

export function ResolveKid200ResponseToJSON(json: any): ResolveKid200Response {
    return ResolveKid200ResponseToJSONTyped(json, false);
}

export function ResolveKid200ResponseToJSONTyped(value?: ResolveKid200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kid_document': KidDocumentToJSON(value['kidDocument']),
        'manifest_document': CapabilityManifestToJSON(value['manifestDocument']),
    };
}

