/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VdfProof } from './VdfProof';
import {
    VdfProofFromJSON,
    VdfProofFromJSONTyped,
    VdfProofToJSON,
    VdfProofToJSONTyped,
} from './VdfProof';
import type { PreviousProof } from './PreviousProof';
import {
    PreviousProofFromJSON,
    PreviousProofFromJSONTyped,
    PreviousProofToJSON,
    PreviousProofToJSONTyped,
} from './PreviousProof';

/**
 * 
 * @export
 * @interface Reveal
 */
export interface Reveal {
    /**
     * 
     * @type {number}
     * @memberof Reveal
     */
    protocolVersion: number;
    /**
     * 
     * @type {string}
     * @memberof Reveal
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Reveal
     */
    payload: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Reveal
     */
    salt: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Reveal
     */
    drandPulse: number;
    /**
     * 
     * @type {string}
     * @memberof Reveal
     */
    drandRandomness: string;
    /**
     * 
     * @type {number}
     * @memberof Reveal
     */
    iterations: number;
    /**
     * 
     * @type {VdfProof}
     * @memberof Reveal
     */
    vdfProof: VdfProof;
    /**
     * 
     * @type {Array<number>}
     * @memberof Reveal
     */
    pubkey: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Reveal
     */
    signature: Array<number>;
    /**
     * 
     * @type {PreviousProof}
     * @memberof Reveal
     */
    previousProof?: PreviousProof;
    /**
     * 
     * @type {Array<number>}
     * @memberof Reveal
     */
    minerPubkey?: Array<number> | null;
}

/**
 * Check if a given object implements the Reveal interface.
 */
export function instanceOfReveal(value: object): value is Reveal {
    if ((!('protocolVersion' in value) && !('protocol_version' in value)) || (value['protocolVersion'] === undefined && value['protocol_version'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('salt' in value) || value['salt'] === undefined) return false;
    if ((!('drandPulse' in value) && !('drand_pulse' in value)) || (value['drandPulse'] === undefined && value['drand_pulse'] === undefined)) return false;
    if ((!('drandRandomness' in value) && !('drand_randomness' in value)) || (value['drandRandomness'] === undefined && value['drand_randomness'] === undefined)) return false;
    if (!('iterations' in value) || value['iterations'] === undefined) return false;
    if ((!('vdfProof' in value) && !('vdf_proof' in value)) || (value['vdfProof'] === undefined && value['vdf_proof'] === undefined)) return false;
    if (!('pubkey' in value) || value['pubkey'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function RevealFromJSON(json: any): Reveal {
    return RevealFromJSONTyped(json, false);
}

export function RevealFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reveal {
    if (json == null) {
        return json;
    }
    return {
        
        'protocolVersion': json['protocol_version'],
        'name': json['name'],
        'payload': json['payload'],
        'salt': json['salt'],
        'drandPulse': json['drand_pulse'],
        'drandRandomness': json['drand_randomness'],
        'iterations': json['iterations'],
        'vdfProof': VdfProofFromJSON(json['vdf_proof']),
        'pubkey': json['pubkey'],
        'signature': json['signature'],
        'previousProof': json['previous_proof'] == null ? undefined : PreviousProofFromJSON(json['previous_proof']),
        'minerPubkey': json['miner_pubkey'] == null ? undefined : json['miner_pubkey'],
    };
}

export function RevealToJSON(json: any): Reveal {
    return RevealToJSONTyped(json, false);
}

export function RevealToJSONTyped(value?: Reveal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol_version': value['protocolVersion'],
        'name': value['name'],
        'payload': value['payload'],
        'salt': value['salt'],
        'drand_pulse': value['drandPulse'],
        'drand_randomness': value['drandRandomness'],
        'iterations': value['iterations'],
        'vdf_proof': VdfProofToJSON(value['vdfProof']),
        'pubkey': value['pubkey'],
        'signature': value['signature'],
        'previous_proof': PreviousProofToJSON(value['previousProof']),
        'miner_pubkey': value['minerPubkey'],
    };
}

