/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConfigRequest
 */
export interface UpdateConfigRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateConfigRequest
     */
    mode?: string;
}

/**
 * Check if a given object implements the UpdateConfigRequest interface.
 */
export function instanceOfUpdateConfigRequest(value: object): value is UpdateConfigRequest {
    return true;
}

export function UpdateConfigRequestFromJSON(json: any): UpdateConfigRequest {
    return UpdateConfigRequestFromJSONTyped(json, false);
}

export function UpdateConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function UpdateConfigRequestToJSON(json: any): UpdateConfigRequest {
    return UpdateConfigRequestToJSONTyped(json, false);
}

export function UpdateConfigRequestToJSONTyped(value?: UpdateConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

