/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VdfProof
 */
export interface VdfProof {
    /**
     * 
     * @type {Array<number>}
     * @memberof VdfProof
     */
    proofBytes: Array<number>;
}

/**
 * Check if a given object implements the VdfProof interface.
 */
export function instanceOfVdfProof(value: object): value is VdfProof {
    if ((!('proofBytes' in value) && !('proof_bytes' in value)) || (value['proofBytes'] === undefined && value['proof_bytes'] === undefined)) return false;
    return true;
}

export function VdfProofFromJSON(json: any): VdfProof {
    return VdfProofFromJSONTyped(json, false);
}

export function VdfProofFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdfProof {
    if (json == null) {
        return json;
    }
    return {
        
        'proofBytes': json['proof_bytes'],
    };
}

export function VdfProofToJSON(json: any): VdfProof {
    return VdfProofToJSONTyped(json, false);
}

export function VdfProofToJSONTyped(value?: VdfProof | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proof_bytes': value['proofBytes'],
    };
}

