/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VdfRegisterPost200Response
 */
export interface VdfRegisterPost200Response {
    /**
     * 
     * @type {string}
     * @memberof VdfRegisterPost200Response
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof VdfRegisterPost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the VdfRegisterPost200Response interface.
 */
export function instanceOfVdfRegisterPost200Response(value: object): value is VdfRegisterPost200Response {
    return true;
}

export function VdfRegisterPost200ResponseFromJSON(json: any): VdfRegisterPost200Response {
    return VdfRegisterPost200ResponseFromJSONTyped(json, false);
}

export function VdfRegisterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdfRegisterPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function VdfRegisterPost200ResponseToJSON(json: any): VdfRegisterPost200Response {
    return VdfRegisterPost200ResponseToJSONTyped(json, false);
}

export function VdfRegisterPost200ResponseToJSONTyped(value?: VdfRegisterPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
        'message': value['message'],
    };
}

