/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VdfRegisterRequest
 */
export interface VdfRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof VdfRegisterRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof VdfRegisterRequest
     */
    iterations?: number | null;
}

/**
 * Check if a given object implements the VdfRegisterRequest interface.
 */
export function instanceOfVdfRegisterRequest(value: object): value is VdfRegisterRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function VdfRegisterRequestFromJSON(json: any): VdfRegisterRequest {
    return VdfRegisterRequestFromJSONTyped(json, false);
}

export function VdfRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdfRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'iterations': json['iterations'] == null ? undefined : json['iterations'],
    };
}

export function VdfRegisterRequestToJSON(json: any): VdfRegisterRequest {
    return VdfRegisterRequestToJSONTyped(json, false);
}

export function VdfRegisterRequestToJSONTyped(value?: VdfRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'iterations': value['iterations'],
    };
}

