/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VdfStatusTaskIdDelete200Response
 */
export interface VdfStatusTaskIdDelete200Response {
    /**
     * 
     * @type {boolean}
     * @memberof VdfStatusTaskIdDelete200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the VdfStatusTaskIdDelete200Response interface.
 */
export function instanceOfVdfStatusTaskIdDelete200Response(value: object): value is VdfStatusTaskIdDelete200Response {
    return true;
}

export function VdfStatusTaskIdDelete200ResponseFromJSON(json: any): VdfStatusTaskIdDelete200Response {
    return VdfStatusTaskIdDelete200ResponseFromJSONTyped(json, false);
}

export function VdfStatusTaskIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdfStatusTaskIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function VdfStatusTaskIdDelete200ResponseToJSON(json: any): VdfStatusTaskIdDelete200Response {
    return VdfStatusTaskIdDelete200ResponseToJSONTyped(json, false);
}

export function VdfStatusTaskIdDelete200ResponseToJSONTyped(value?: VdfStatusTaskIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

