/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VdfTaskStatus
 */
export interface VdfTaskStatus {
    /**
     * 
     * @type {string}
     * @memberof VdfTaskStatus
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof VdfTaskStatus
     */
    iterations: number;
    /**
     * 
     * @type {number}
     * @memberof VdfTaskStatus
     */
    progress: number;
    /**
     * 
     * @type {string}
     * @memberof VdfTaskStatus
     */
    error?: string | null;
}

/**
 * Check if a given object implements the VdfTaskStatus interface.
 */
export function instanceOfVdfTaskStatus(value: object): value is VdfTaskStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('iterations' in value) || value['iterations'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function VdfTaskStatusFromJSON(json: any): VdfTaskStatus {
    return VdfTaskStatusFromJSONTyped(json, false);
}

export function VdfTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdfTaskStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'iterations': json['iterations'],
        'progress': json['progress'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function VdfTaskStatusToJSON(json: any): VdfTaskStatus {
    return VdfTaskStatusToJSONTyped(json, false);
}

export function VdfTaskStatusToJSONTyped(value?: VdfTaskStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'iterations': value['iterations'],
        'progress': value['progress'],
        'error': value['error'],
    };
}

