/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSession {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "app_name")]
    pub app_name: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "expiry_kyn")]
    pub expiry_kyn: i32,
}

impl AppSession {
    pub fn new(id: String, token: String, app_name: String, scopes: Vec<String>, created_at: i32, expiry_kyn: i32) -> AppSession {
        AppSession {
            id,
            token,
            app_name,
            scopes,
            created_at,
            expiry_kyn,
        }
    }
}

