/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizedManifest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "manifest")]
    pub manifest: Box<models::CapabilityManifest>,
    #[serde(rename = "owner_signature")]
    pub owner_signature: Vec<i32>,
}

impl AuthorizedManifest {
    pub fn new(name: String, manifest: models::CapabilityManifest, owner_signature: Vec<i32>) -> AuthorizedManifest {
        AuthorizedManifest {
            name,
            manifest: Box::new(manifest),
            owner_signature,
        }
    }
}

