/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizedKid {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kid_doc")]
    pub kid_doc: Box<models::KidDocument>,
    #[serde(rename = "owner_signature")]
    pub owner_signature: Vec<i32>,
}

impl AuthorizedKid {
    pub fn new(name: String, kid_doc: models::KidDocument, owner_signature: Vec<i32>) -> AuthorizedKid {
        AuthorizedKid {
            name,
            kid_doc: Box::new(kid_doc),
            owner_signature,
        }
    }
}

