/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityManifest {
    #[serde(rename = "doc_type")]
    pub doc_type: String,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "valid_from")]
    pub valid_from: i32,
    #[serde(rename = "services")]
    pub services: Vec<serde_json::Value>,
    #[serde(rename = "signature", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Option<String>>,
}

impl CapabilityManifest {
    pub fn new(doc_type: String, kid: String, version: i32, valid_from: i32, services: Vec<serde_json::Value>) -> CapabilityManifest {
        CapabilityManifest {
            doc_type,
            kid,
            version,
            valid_from,
            services,
            signature: None,
        }
    }
}

