/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "commitment")]
    pub commitment: Box<models::Commitment>,
}

impl CommitRequest {
    pub fn new(name: String, commitment: models::Commitment) -> CommitRequest {
        CommitRequest {
            name,
            commitment: Box::new(commitment),
        }
    }
}

