/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Commitment {
    #[serde(rename = "hash")]
    pub hash: Vec<i32>,
}

impl Commitment {
    pub fn new(hash: Vec<i32>) -> Commitment {
        Commitment {
            hash,
        }
    }
}

