/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigResponse : Response body for GET /config.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigResponse {
    /// Always "ok" on success.
    #[serde(rename = "status")]
    pub status: String,

    /// Active network mode of the daemon (e.g. "mainnet", "testnet").
    #[serde(rename = "mode")]
    pub mode: String,
}

impl ConfigResponse {
    /// Creates a new `ConfigResponse`.
    pub fn new(status: String, mode: String) -> ConfigResponse {
        ConfigResponse { status, mode }
    }
}
