/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSession200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl CreateSession200Response {
    pub fn new() -> CreateSession200Response {
        CreateSession200Response {
            status: None,
            id: None,
            token: None,
        }
    }
}

