/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequest {
    #[serde(rename = "app_name")]
    pub app_name: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<Scopes>,
    #[serde(rename = "expiry_kyn")]
    pub expiry_kyn: i32,
}

impl CreateSessionRequest {
    pub fn new(app_name: String, scopes: Vec<Scopes>, expiry_kyn: i32) -> CreateSessionRequest {
        CreateSessionRequest {
            app_name,
            scopes,
            expiry_kyn,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scopes {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "kid")]
    Kid,
    #[serde(rename = "nrs")]
    Nrs,
    #[serde(rename = "vdf")]
    Vdf,
    #[serde(rename = "action")]
    Action,
    #[serde(rename = "gossip")]
    Gossip,
    #[serde(rename = "metric")]
    Metric,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "atlas")]
    Atlas,
}

impl Default for Scopes {
    fn default() -> Scopes {
        Self::Admin
    }
}

