/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateKidRequest {
    #[serde(rename = "base_name")]
    pub base_name: String,
    #[serde(rename = "sub_name", skip_serializing_if = "Option::is_none")]
    pub sub_name: Option<String>,
    #[serde(rename = "inherit_subname", skip_serializing_if = "Option::is_none")]
    pub inherit_subname: Option<bool>,
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

impl GenerateKidRequest {
    pub fn new(base_name: String) -> GenerateKidRequest {
        GenerateKidRequest {
            base_name,
            sub_name: None,
            inherit_subname: None,
            force: None,
        }
    }
}

