/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBannedPeers200ResponseBannedPeersInner {
    #[serde(rename = "peer_id", skip_serializing_if = "Option::is_none")]
    pub peer_id: Option<String>,
    #[serde(rename = "expires_at_kyn", skip_serializing_if = "Option::is_none")]
    pub expires_at_kyn: Option<i32>,
}

impl GetBannedPeers200ResponseBannedPeersInner {
    pub fn new() -> GetBannedPeers200ResponseBannedPeersInner {
        GetBannedPeers200ResponseBannedPeersInner {
            peer_id: None,
            expires_at_kyn: None,
        }
    }
}

