/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHeartbeats200ResponseNamesInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "latest_kyn", skip_serializing_if = "Option::is_none")]
    pub latest_kyn: Option<i32>,
    #[serde(rename = "kyns_idle", skip_serializing_if = "Option::is_none")]
    pub kyns_idle: Option<i32>,
}

impl GetHeartbeats200ResponseNamesInner {
    pub fn new() -> GetHeartbeats200ResponseNamesInner {
        GetHeartbeats200ResponseNamesInner {
            name: None,
            status: None,
            latest_kyn: None,
            kyns_idle: None,
        }
    }
}

