/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVdfTasks200ResponseValue {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
    #[serde(rename = "eta_seconds", skip_serializing_if = "Option::is_none")]
    pub eta_seconds: Option<i32>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl GetVdfTasks200ResponseValue {
    pub fn new() -> GetVdfTasks200ResponseValue {
        GetVdfTasks200ResponseValue {
            status: None,
            percent: None,
            eta_seconds: None,
            error: None,
        }
    }
}

