/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConsensusDifficulty200Response {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "label_length", skip_serializing_if = "Option::is_none")]
    pub label_length: Option<i32>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Box<models::GetConsensusDifficulty200ResponseProtocol>>,
    #[serde(rename = "local_prediction", skip_serializing_if = "Option::is_none")]
    pub local_prediction: Option<Box<models::GetConsensusDifficulty200ResponseLocalPrediction>>,
}

impl GetConsensusDifficulty200Response {
    pub fn new() -> GetConsensusDifficulty200Response {
        GetConsensusDifficulty200Response {
            name: None,
            label: None,
            label_length: None,
            protocol: None,
            local_prediction: None,
        }
    }
}

