/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActionStatus200Response {
    #[serde(rename = "genesis_kyn", skip_serializing_if = "Option::is_none")]
    pub genesis_kyn: Option<i32>,
    #[serde(rename = "active_sovereign_key_hex", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub active_sovereign_key_hex: Option<Option<String>>,
    #[serde(rename = "is_halted", skip_serializing_if = "Option::is_none")]
    pub is_halted: Option<bool>,
    #[serde(rename = "halt_start_kyn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub halt_start_kyn: Option<Option<i32>>,
    #[serde(rename = "total_paused_kyns", skip_serializing_if = "Option::is_none")]
    pub total_paused_kyns: Option<i32>,
}

impl GetActionStatus200Response {
    pub fn new() -> GetActionStatus200Response {
        GetActionStatus200Response {
            genesis_kyn: None,
            active_sovereign_key_hex: None,
            is_halted: None,
            halt_start_kyn: None,
            total_paused_kyns: None,
        }
    }
}

