/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTakeoverDifficulty200Response {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "base_iterations", skip_serializing_if = "Option::is_none")]
    pub base_iterations: Option<i32>,
    #[serde(rename = "kyns_idle", skip_serializing_if = "Option::is_none")]
    pub kyns_idle: Option<i32>,
    #[serde(rename = "current_iterations", skip_serializing_if = "Option::is_none")]
    pub current_iterations: Option<i32>,
    #[serde(rename = "decay_multiplier", skip_serializing_if = "Option::is_none")]
    pub decay_multiplier: Option<f64>,
}

impl GetTakeoverDifficulty200Response {
    pub fn new() -> GetTakeoverDifficulty200Response {
        GetTakeoverDifficulty200Response {
            name: None,
            base_iterations: None,
            kyns_idle: None,
            current_iterations: None,
            decay_multiplier: None,
        }
    }
}

