/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConsensusDifficulty200ResponseProtocol {
    #[serde(rename = "iterations", skip_serializing_if = "Option::is_none")]
    pub iterations: Option<i32>,
    #[serde(rename = "ndc_tier", skip_serializing_if = "Option::is_none")]
    pub ndc_tier: Option<String>,
    #[serde(rename = "network_reference_target_minutes", skip_serializing_if = "Option::is_none")]
    pub network_reference_target_minutes: Option<i32>,
    #[serde(rename = "is_dev_mode", skip_serializing_if = "Option::is_none")]
    pub is_dev_mode: Option<bool>,
}

impl GetConsensusDifficulty200ResponseProtocol {
    pub fn new() -> GetConsensusDifficulty200ResponseProtocol {
        GetConsensusDifficulty200ResponseProtocol {
            iterations: None,
            ndc_tier: None,
            network_reference_target_minutes: None,
            is_dev_mode: None,
        }
    }
}

