/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBannedPeers200Response {
    #[serde(rename = "banned_peers", skip_serializing_if = "Option::is_none")]
    pub banned_peers: Option<Vec<models::GetBannedPeers200ResponseBannedPeersInner>>,
}

impl GetBannedPeers200Response {
    pub fn new() -> GetBannedPeers200Response {
        GetBannedPeers200Response {
            banned_peers: None,
        }
    }
}

