/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHeartbeats200Response {
    #[serde(rename = "current_kyn", skip_serializing_if = "Option::is_none")]
    pub current_kyn: Option<i32>,
    #[serde(rename = "names", skip_serializing_if = "Option::is_none")]
    pub names: Option<Vec<models::GetHeartbeats200ResponseNamesInner>>,
}

impl GetHeartbeats200Response {
    pub fn new() -> GetHeartbeats200Response {
        GetHeartbeats200Response {
            current_kyn: None,
            names: None,
        }
    }
}

