/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetworkNat200Response {
    #[serde(rename = "nat_status", skip_serializing_if = "Option::is_none")]
    pub nat_status: Option<String>,
}

impl GetNetworkNat200Response {
    pub fn new() -> GetNetworkNat200Response {
        GetNetworkNat200Response {
            nat_status: None,
        }
    }
}

