/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KidDocument {
    #[serde(rename = "doc_type")]
    pub doc_type: String,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "controller_keys")]
    pub controller_keys: Vec<String>,
    #[serde(rename = "manifest", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<Option<serde_json::Value>>,
    #[serde(rename = "revocation_keys")]
    pub revocation_keys: Vec<String>,
    #[serde(rename = "signature", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Option<String>>,
}

impl KidDocument {
    pub fn new(doc_type: String, kid: String, created_at: i32, controller_keys: Vec<String>, revocation_keys: Vec<String>) -> KidDocument {
        KidDocument {
            doc_type,
            kid,
            created_at,
            controller_keys,
            manifest: None,
            revocation_keys,
            signature: None,
        }
    }
}

