/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSessionsResponse {
    #[serde(rename = "sessions")]
    pub sessions: Vec<models::AppSession>,
}

impl ListSessionsResponse {
    pub fn new(sessions: Vec<models::AppSession>) -> ListSessionsResponse {
        ListSessionsResponse {
            sessions,
        }
    }
}

