/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NameEnvelope {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "payload_bytes", skip_serializing_if = "Option::is_none")]
    pub payload_bytes: Option<Vec<u8>>,
    #[serde(rename = "signature_hex", skip_serializing_if = "Option::is_none")]
    pub signature_hex: Option<String>,
    #[serde(rename = "kyn", skip_serializing_if = "Option::is_none")]
    pub kyn: Option<i32>,
}

impl NameEnvelope {
    pub fn new() -> NameEnvelope {
        NameEnvelope {
            name: None,
            payload_bytes: None,
            signature_hex: None,
            kyn: None,
        }
    }
}

