/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NrsZone {
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<std::collections::HashMap<String, Vec<models::NrsEntry>>>,
}

impl NrsZone {
    pub fn new() -> NrsZone {
        NrsZone {
            records: None,
        }
    }
}

