/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NrsRecord {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "value")]
    pub value: String,
}

impl NrsRecord {
    pub fn new(r#type: Type, value: String) -> NrsRecord {
        NrsRecord {
            r#type,
            value,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "AAAA")]
    Aaaa,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "PeerId")]
    PeerId,
    #[serde(rename = "KID")]
    Kid,
}

impl Default for Type {
    fn default() -> Type {
        Self::A
    }
}

