/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostHeartbeat200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "kyn", skip_serializing_if = "Option::is_none")]
    pub kyn: Option<i32>,
}

impl PostHeartbeat200Response {
    pub fn new() -> PostHeartbeat200Response {
        PostHeartbeat200Response {
            status: None,
            message: None,
            kyn: None,
        }
    }
}

