/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostFatHeartbeatRequest {
    #[serde(rename = "hot_key_hex", skip_serializing_if = "Option::is_none")]
    pub hot_key_hex: Option<String>,
    #[serde(rename = "authorized_manifest", skip_serializing_if = "Option::is_none")]
    pub authorized_manifest: Option<serde_json::Value>,
}

impl PostFatHeartbeatRequest {
    pub fn new() -> PostFatHeartbeatRequest {
        PostFatHeartbeatRequest {
            hot_key_hex: None,
            authorized_manifest: None,
        }
    }
}

