/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviousProof {
    #[serde(rename = "salt")]
    pub salt: Vec<i32>,
    #[serde(rename = "kyn")]
    pub kyn: i32,
    #[serde(rename = "drand_signature")]
    pub drand_signature: String,
    #[serde(rename = "iterations")]
    pub iterations: i32,
    #[serde(rename = "vdf_proof")]
    pub vdf_proof: Box<models::VdfProof>,
    #[serde(rename = "signature")]
    pub signature: Vec<i32>,
}

impl PreviousProof {
    pub fn new(salt: Vec<i32>, kyn: i32, drand_signature: String, iterations: i32, vdf_proof: models::VdfProof, signature: Vec<i32>) -> PreviousProof {
        PreviousProof {
            salt,
            kyn,
            drand_signature,
            iterations,
            vdf_proof: Box::new(vdf_proof),
            signature,
        }
    }
}

