/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishRequest {
    #[serde(rename = "reveal")]
    pub reveal: Box<models::Reveal>,
}

impl PublishRequest {
    pub fn new(reveal: models::Reveal) -> PublishRequest {
        PublishRequest {
            reveal: Box::new(reveal),
        }
    }
}

