/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolveKid200Response {
    #[serde(rename = "kid_document", skip_serializing_if = "Option::is_none")]
    pub kid_document: Option<Box<models::KidDocument>>,
    #[serde(rename = "manifest_document", skip_serializing_if = "Option::is_none")]
    pub manifest_document: Option<Box<models::CapabilityManifest>>,
}

impl ResolveKid200Response {
    pub fn new() -> ResolveKid200Response {
        ResolveKid200Response {
            kid_document: None,
            manifest_document: None,
        }
    }
}

