/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reveal {
    #[serde(rename = "protocol_version")]
    pub protocol_version: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "payload")]
    pub payload: Vec<i32>,
    #[serde(rename = "salt")]
    pub salt: Vec<i32>,
    #[serde(rename = "kyn")]
    pub kyn: i32,
    #[serde(rename = "drand_signature")]
    pub drand_signature: String,
    #[serde(rename = "iterations")]
    pub iterations: i32,
    #[serde(rename = "vdf_proof")]
    pub vdf_proof: Box<models::VdfProof>,
    #[serde(rename = "pubkey")]
    pub pubkey: Vec<i32>,
    #[serde(rename = "signature")]
    pub signature: Vec<i32>,
    #[serde(rename = "previous_proof", skip_serializing_if = "Option::is_none")]
    pub previous_proof: Option<Box<models::PreviousProof>>,
    #[serde(rename = "miner_pubkey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub miner_pubkey: Option<Option<Vec<i32>>>,
}

impl Reveal {
    pub fn new(protocol_version: i32, name: String, payload: Vec<i32>, salt: Vec<i32>, kyn: i32, drand_signature: String, iterations: i32, vdf_proof: models::VdfProof, pubkey: Vec<i32>, signature: Vec<i32>) -> Reveal {
        Reveal {
            protocol_version,
            name,
            payload,
            salt,
            kyn,
            drand_signature,
            iterations,
            vdf_proof: Box::new(vdf_proof),
            pubkey,
            signature,
            previous_proof: None,
            miner_pubkey: None,
        }
    }
}

