/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateName200Response {
    #[serde(rename = "original", skip_serializing_if = "Option::is_none")]
    pub original: Option<String>,
    #[serde(rename = "normalized", skip_serializing_if = "Option::is_none")]
    pub normalized: Option<String>,
    #[serde(rename = "is_valid", skip_serializing_if = "Option::is_none")]
    pub is_valid: Option<bool>,
    #[serde(rename = "is_reserved", skip_serializing_if = "Option::is_none")]
    pub is_reserved: Option<bool>,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<String>>,
}

impl ValidateName200Response {
    pub fn new() -> ValidateName200Response {
        ValidateName200Response {
            original: None,
            normalized: None,
            is_valid: None,
            is_reserved: None,
            error: None,
        }
    }
}

