/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VdfRegisterRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "iterations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iterations: Option<Option<i32>>,
}

impl VdfRegisterRequest {
    pub fn new(name: String) -> VdfRegisterRequest {
        VdfRegisterRequest {
            name,
            iterations: None,
        }
    }
}

