/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VdfProof {
    #[serde(rename = "proof_bytes")]
    pub proof_bytes: Vec<i32>,
}

impl VdfProof {
    pub fn new(proof_bytes: Vec<i32>) -> VdfProof {
        VdfProof {
            proof_bytes,
        }
    }
}

