/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VdfTaskStatus {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "iterations")]
    pub iterations: i32,
    #[serde(rename = "progress")]
    pub progress: i32,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<String>>,
}

impl VdfTaskStatus {
    pub fn new(status: String, iterations: i32, progress: i32) -> VdfTaskStatus {
        VdfTaskStatus {
            status,
            iterations,
            progress,
            error: None,
        }
    }
}

