/*
 * Kinetic Daemon API
 *
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyQuorum200Response {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "quorum_count", skip_serializing_if = "Option::is_none")]
    pub quorum_count: Option<i32>,
}

impl VerifyQuorum200Response {
    pub fn new() -> VerifyQuorum200Response {
        VerifyQuorum200Response {
            name: None,
            quorum_count: None,
        }
    }
}

