/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KidDocument } from './KidDocument';
import {
    KidDocumentFromJSON,
    KidDocumentFromJSONTyped,
    KidDocumentToJSON,
    KidDocumentToJSONTyped,
} from './KidDocument';

/**
 * 
 * @export
 * @interface AuthorizedKid
 */
export interface AuthorizedKid {
    /**
     * 
     * @type {string}
     * @memberof AuthorizedKid
     */
    name: string;
    /**
     * 
     * @type {KidDocument}
     * @memberof AuthorizedKid
     */
    kidDoc: KidDocument;
    /**
     * 
     * @type {Array<number>}
     * @memberof AuthorizedKid
     */
    ownerSignature: Array<number>;
}

/**
 * Check if a given object implements the AuthorizedKid interface.
 */
export function instanceOfAuthorizedKid(value: object): value is AuthorizedKid {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('kidDoc' in value) && !('kid_doc' in value)) || (value['kidDoc'] === undefined && value['kid_doc'] === undefined)) return false;
    if ((!('ownerSignature' in value) && !('owner_signature' in value)) || (value['ownerSignature'] === undefined && value['owner_signature'] === undefined)) return false;
    return true;
}

export function AuthorizedKidFromJSON(json: any): AuthorizedKid {
    return AuthorizedKidFromJSONTyped(json, false);
}

export function AuthorizedKidFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizedKid {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'kidDoc': KidDocumentFromJSON(json['kid_doc']),
        'ownerSignature': json['owner_signature'],
    };
}

export function AuthorizedKidToJSON(json: any): AuthorizedKid {
    return AuthorizedKidToJSONTyped(json, false);
}

export function AuthorizedKidToJSONTyped(value?: AuthorizedKid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'kid_doc': KidDocumentToJSON(value['kidDoc']),
        'owner_signature': value['ownerSignature'],
    };
}

