/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Commitment } from './Commitment';
import {
    CommitmentFromJSON,
    CommitmentFromJSONTyped,
    CommitmentToJSON,
    CommitmentToJSONTyped,
} from './Commitment';

/**
 * 
 * @export
 * @interface CommitRequest
 */
export interface CommitRequest {
    /**
     * 
     * @type {string}
     * @memberof CommitRequest
     */
    name: string;
    /**
     * 
     * @type {Commitment}
     * @memberof CommitRequest
     */
    commitment: Commitment;
}

/**
 * Check if a given object implements the CommitRequest interface.
 */
export function instanceOfCommitRequest(value: object): value is CommitRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('commitment' in value) || value['commitment'] === undefined) return false;
    return true;
}

export function CommitRequestFromJSON(json: any): CommitRequest {
    return CommitRequestFromJSONTyped(json, false);
}

export function CommitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'commitment': CommitmentFromJSON(json['commitment']),
    };
}

export function CommitRequestToJSON(json: any): CommitRequest {
    return CommitRequestToJSONTyped(json, false);
}

export function CommitRequestToJSONTyped(value?: CommitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'commitment': CommitmentToJSON(value['commitment']),
    };
}

