/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigPostRequest
 */
export interface ConfigPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfigPostRequest
     */
    mode?: string;
}

/**
 * Check if a given object implements the ConfigPostRequest interface.
 */
export function instanceOfConfigPostRequest(value: object): value is ConfigPostRequest {
    return true;
}

export function ConfigPostRequestFromJSON(json: any): ConfigPostRequest {
    return ConfigPostRequestFromJSONTyped(json, false);
}

export function ConfigPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function ConfigPostRequestToJSON(json: any): ConfigPostRequest {
    return ConfigPostRequestToJSONTyped(json, false);
}

export function ConfigPostRequestToJSONTyped(value?: ConfigPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

