/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DnsRecord } from './DnsRecord';
import {
    DnsRecordFromJSON,
    DnsRecordFromJSONTyped,
    DnsRecordToJSON,
    DnsRecordToJSONTyped,
} from './DnsRecord';

/**
 * 
 * @export
 * @interface DnsZone
 */
export interface DnsZone {
    /**
     * 
     * @type {{ [key: string]: Array<DnsRecord>; }}
     * @memberof DnsZone
     */
    records?: { [key: string]: Array<DnsRecord>; };
}

/**
 * Check if a given object implements the DnsZone interface.
 */
export function instanceOfDnsZone(value: object): value is DnsZone {
    return true;
}

export function DnsZoneFromJSON(json: any): DnsZone {
    return DnsZoneFromJSONTyped(json, false);
}

export function DnsZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsZone {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : json['records'],
    };
}

export function DnsZoneToJSON(json: any): DnsZone {
    return DnsZoneToJSONTyped(json, false);
}

export function DnsZoneToJSONTyped(value?: DnsZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'],
    };
}

