/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KidDocument
 */
export interface KidDocument {
    /**
     * 
     * @type {string}
     * @memberof KidDocument
     */
    docType: string;
    /**
     * 
     * @type {string}
     * @memberof KidDocument
     */
    kid: string;
    /**
     * 
     * @type {number}
     * @memberof KidDocument
     */
    createdAt: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof KidDocument
     */
    controllerKeys: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof KidDocument
     */
    manifest?: object | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof KidDocument
     */
    revocationKeys: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KidDocument
     */
    signature?: string | null;
}

/**
 * Check if a given object implements the KidDocument interface.
 */
export function instanceOfKidDocument(value: object): value is KidDocument {
    if ((!('docType' in value) && !('doc_type' in value)) || (value['docType'] === undefined && value['doc_type'] === undefined)) return false;
    if (!('kid' in value) || value['kid'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('controllerKeys' in value) && !('controller_keys' in value)) || (value['controllerKeys'] === undefined && value['controller_keys'] === undefined)) return false;
    if ((!('revocationKeys' in value) && !('revocation_keys' in value)) || (value['revocationKeys'] === undefined && value['revocation_keys'] === undefined)) return false;
    return true;
}

export function KidDocumentFromJSON(json: any): KidDocument {
    return KidDocumentFromJSONTyped(json, false);
}

export function KidDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): KidDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'docType': json['doc_type'],
        'kid': json['kid'],
        'createdAt': json['created_at'],
        'controllerKeys': json['controller_keys'],
        'manifest': json['manifest'] == null ? undefined : json['manifest'],
        'revocationKeys': json['revocation_keys'],
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function KidDocumentToJSON(json: any): KidDocument {
    return KidDocumentToJSONTyped(json, false);
}

export function KidDocumentToJSONTyped(value?: KidDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'doc_type': value['docType'],
        'kid': value['kid'],
        'created_at': value['createdAt'],
        'controller_keys': value['controllerKeys'],
        'manifest': value['manifest'],
        'revocation_keys': value['revocationKeys'],
        'signature': value['signature'],
    };
}

