/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameRenewRequest
 */
export interface NameRenewRequest {
    /**
     * 
     * @type {string}
     * @memberof NameRenewRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NameRenewRequest
     */
    iterations?: number | null;
}

/**
 * Check if a given object implements the NameRenewRequest interface.
 */
export function instanceOfNameRenewRequest(value: object): value is NameRenewRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NameRenewRequestFromJSON(json: any): NameRenewRequest {
    return NameRenewRequestFromJSONTyped(json, false);
}

export function NameRenewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameRenewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'iterations': json['iterations'] == null ? undefined : json['iterations'],
    };
}

export function NameRenewRequestToJSON(json: any): NameRenewRequest {
    return NameRenewRequestToJSONTyped(json, false);
}

export function NameRenewRequestToJSONTyped(value?: NameRenewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'iterations': value['iterations'],
    };
}

