/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapabilityManifest } from './CapabilityManifest';
import {
    CapabilityManifestFromJSON,
    CapabilityManifestFromJSONTyped,
    CapabilityManifestToJSON,
    CapabilityManifestToJSONTyped,
} from './CapabilityManifest';
import type { KidDocument } from './KidDocument';
import {
    KidDocumentFromJSON,
    KidDocumentFromJSONTyped,
    KidDocumentToJSON,
    KidDocumentToJSONTyped,
} from './KidDocument';

/**
 * 
 * @export
 * @interface ResolveKidDidGet200Response
 */
export interface ResolveKidDidGet200Response {
    /**
     * 
     * @type {KidDocument}
     * @memberof ResolveKidDidGet200Response
     */
    kidDocument?: KidDocument;
    /**
     * 
     * @type {CapabilityManifest}
     * @memberof ResolveKidDidGet200Response
     */
    manifestDocument?: CapabilityManifest;
}

/**
 * Check if a given object implements the ResolveKidDidGet200Response interface.
 */
export function instanceOfResolveKidDidGet200Response(value: object): value is ResolveKidDidGet200Response {
    return true;
}

export function ResolveKidDidGet200ResponseFromJSON(json: any): ResolveKidDidGet200Response {
    return ResolveKidDidGet200ResponseFromJSONTyped(json, false);
}

export function ResolveKidDidGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveKidDidGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'kidDocument': json['kid_document'] == null ? undefined : KidDocumentFromJSON(json['kid_document']),
        'manifestDocument': json['manifest_document'] == null ? undefined : CapabilityManifestFromJSON(json['manifest_document']),
    };
}

export function ResolveKidDidGet200ResponseToJSON(json: any): ResolveKidDidGet200Response {
    return ResolveKidDidGet200ResponseToJSONTyped(json, false);
}

export function ResolveKidDidGet200ResponseToJSONTyped(value?: ResolveKidDidGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kid_document': KidDocumentToJSON(value['kidDocument']),
        'manifest_document': CapabilityManifestToJSON(value['manifestDocument']),
    };
}

