/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AuthorizedKid,
    AuthorizedKidFromJSON,
    AuthorizedKidToJSON,
} from '../models/AuthorizedKid';
import {
    type AuthorizedManifest,
    AuthorizedManifestFromJSON,
    AuthorizedManifestToJSON,
} from '../models/AuthorizedManifest';
import {
    type CommitRequest,
    CommitRequestFromJSON,
    CommitRequestToJSON,
} from '../models/CommitRequest';
import {
    type ConfigPostRequest,
    ConfigPostRequestFromJSON,
    ConfigPostRequestToJSON,
} from '../models/ConfigPostRequest';
import {
    type DnsZone,
    DnsZoneFromJSON,
    DnsZoneToJSON,
} from '../models/DnsZone';
import {
    type NameRenewRequest,
    NameRenewRequestFromJSON,
    NameRenewRequestToJSON,
} from '../models/NameRenewRequest';
import {
    type PublishRequest,
    PublishRequestFromJSON,
    PublishRequestToJSON,
} from '../models/PublishRequest';
import {
    type PublishResponse,
    PublishResponseFromJSON,
    PublishResponseToJSON,
} from '../models/PublishResponse';
import {
    type VdfRegisterPost200Response,
    VdfRegisterPost200ResponseFromJSON,
    VdfRegisterPost200ResponseToJSON,
} from '../models/VdfRegisterPost200Response';
import {
    type VdfRegisterRequest,
    VdfRegisterRequestFromJSON,
    VdfRegisterRequestToJSON,
} from '../models/VdfRegisterRequest';
import {
    type VdfStatusTaskIdDelete200Response,
    VdfStatusTaskIdDelete200ResponseFromJSON,
    VdfStatusTaskIdDelete200ResponseToJSON,
} from '../models/VdfStatusTaskIdDelete200Response';
import {
    type VdfTaskStatus,
    VdfTaskStatusFromJSON,
    VdfTaskStatusToJSON,
} from '../models/VdfTaskStatus';

export interface CommitPostRequest {
    commitRequest: CommitRequest;
}

export interface ConfigPostOperationRequest {
    configPostRequest: ConfigPostRequest;
}

export interface PublishKidPostRequest {
    authorizedKid: AuthorizedKid;
}

export interface PublishManifestPostRequest {
    authorizedManifest: AuthorizedManifest;
}

export interface PublishPostRequest {
    publishRequest: PublishRequest;
}

export interface VdfRegisterPostRequest {
    vdfRegisterRequest: VdfRegisterRequest;
}

export interface VdfRenewPostRequest {
    nameRenewRequest: NameRenewRequest;
}

export interface VdfStatusTaskIdDeleteRequest {
    taskId: string;
}

export interface VdfStatusTaskIdGetRequest {
    taskId: string;
}

export interface ZoneNamePostRequest {
    name: string;
    dnsZone: DnsZone;
}

export interface ZoneNamePublishPostRequest {
    name: string;
}

/**
 * 
 */
export class AuthenticatedApi extends runtime.BaseAPI {

    /**
     * Creates request options for commitPost without sending the request
     */
    async commitPostRequestOpts(requestParameters: CommitPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commitRequest'] == null) {
            throw new runtime.RequiredError(
                'commitRequest',
                'Required parameter "commitRequest" was null or undefined when calling commitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commit`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommitRequestToJSON(requestParameters['commitRequest']),
        };
    }

    /**
     * Commit a name hash to DHT
     */
    async commitPostRaw(requestParameters: CommitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.commitPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Commit a name hash to DHT
     */
    async commitPost(requestParameters: CommitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.commitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for configGet without sending the request
     */
    async configGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get config
     */
    async configGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.configGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get config
     */
    async configGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.configGetRaw(initOverrides);
    }

    /**
     * Creates request options for configPost without sending the request
     */
    async configPostRequestOpts(requestParameters: ConfigPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configPostRequest'] == null) {
            throw new runtime.RequiredError(
                'configPostRequest',
                'Required parameter "configPostRequest" was null or undefined when calling configPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfigPostRequestToJSON(requestParameters['configPostRequest']),
        };
    }

    /**
     * Update config
     */
    async configPostRaw(requestParameters: ConfigPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.configPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update config
     */
    async configPost(requestParameters: ConfigPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.configPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ownedNamesGet without sending the request
     */
    async ownedNamesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/owned-names`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of locally owned names
     */
    async ownedNamesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.ownedNamesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get list of locally owned names
     */
    async ownedNamesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.ownedNamesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishKidPost without sending the request
     */
    async publishKidPostRequestOpts(requestParameters: PublishKidPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorizedKid'] == null) {
            throw new runtime.RequiredError(
                'authorizedKid',
                'Required parameter "authorizedKid" was null or undefined when calling publishKidPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish-kid`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorizedKidToJSON(requestParameters['authorizedKid']),
        };
    }

    /**
     * Publish a KID to DHT
     */
    async publishKidPostRaw(requestParameters: PublishKidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishKidPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Publish a KID to DHT
     */
    async publishKidPost(requestParameters: PublishKidPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishKidPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishManifestPost without sending the request
     */
    async publishManifestPostRequestOpts(requestParameters: PublishManifestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorizedManifest'] == null) {
            throw new runtime.RequiredError(
                'authorizedManifest',
                'Required parameter "authorizedManifest" was null or undefined when calling publishManifestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish-manifest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorizedManifestToJSON(requestParameters['authorizedManifest']),
        };
    }

    /**
     * Publish a Capability Manifest to DHT
     */
    async publishManifestPostRaw(requestParameters: PublishManifestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishManifestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Publish a Capability Manifest to DHT
     */
    async publishManifestPost(requestParameters: PublishManifestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishManifestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishPost without sending the request
     */
    async publishPostRequestOpts(requestParameters: PublishPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['publishRequest'] == null) {
            throw new runtime.RequiredError(
                'publishRequest',
                'Required parameter "publishRequest" was null or undefined when calling publishPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PublishRequestToJSON(requestParameters['publishRequest']),
        };
    }

    /**
     * Publish a name reveal to DHT
     */
    async publishPostRaw(requestParameters: PublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Publish a name reveal to DHT
     */
    async publishPost(requestParameters: PublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vdfRegisterPost without sending the request
     */
    async vdfRegisterPostRequestOpts(requestParameters: VdfRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['vdfRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'vdfRegisterRequest',
                'Required parameter "vdfRegisterRequest" was null or undefined when calling vdfRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VdfRegisterRequestToJSON(requestParameters['vdfRegisterRequest']),
        };
    }

    /**
     * Start VDF name registration task
     */
    async vdfRegisterPostRaw(requestParameters: VdfRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfRegisterPost200Response>> {
        const requestOptions = await this.vdfRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfRegisterPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Start VDF name registration task
     */
    async vdfRegisterPost(requestParameters: VdfRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfRegisterPost200Response> {
        const response = await this.vdfRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vdfRenewPost without sending the request
     */
    async vdfRenewPostRequestOpts(requestParameters: VdfRenewPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nameRenewRequest'] == null) {
            throw new runtime.RequiredError(
                'nameRenewRequest',
                'Required parameter "nameRenewRequest" was null or undefined when calling vdfRenewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/renew`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NameRenewRequestToJSON(requestParameters['nameRenewRequest']),
        };
    }

    /**
     * Start VDF name renewal task
     */
    async vdfRenewPostRaw(requestParameters: VdfRenewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfRegisterPost200Response>> {
        const requestOptions = await this.vdfRenewPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfRegisterPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Start VDF name renewal task
     */
    async vdfRenewPost(requestParameters: VdfRenewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfRegisterPost200Response> {
        const response = await this.vdfRenewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vdfStatusTaskIdDelete without sending the request
     */
    async vdfStatusTaskIdDeleteRequestOpts(requestParameters: VdfStatusTaskIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling vdfStatusTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/status/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a VDF task from memory
     */
    async vdfStatusTaskIdDeleteRaw(requestParameters: VdfStatusTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfStatusTaskIdDelete200Response>> {
        const requestOptions = await this.vdfStatusTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfStatusTaskIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a VDF task from memory
     */
    async vdfStatusTaskIdDelete(requestParameters: VdfStatusTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfStatusTaskIdDelete200Response> {
        const response = await this.vdfStatusTaskIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vdfStatusTaskIdGet without sending the request
     */
    async vdfStatusTaskIdGetRequestOpts(requestParameters: VdfStatusTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling vdfStatusTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/status/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get status of a VDF task
     */
    async vdfStatusTaskIdGetRaw(requestParameters: VdfStatusTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfTaskStatus>> {
        const requestOptions = await this.vdfStatusTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfTaskStatusFromJSON(jsonValue));
    }

    /**
     * Get status of a VDF task
     */
    async vdfStatusTaskIdGet(requestParameters: VdfStatusTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfTaskStatus> {
        const response = await this.vdfStatusTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for zoneNamePost without sending the request
     */
    async zoneNamePostRequestOpts(requestParameters: ZoneNamePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling zoneNamePost().'
            );
        }

        if (requestParameters['dnsZone'] == null) {
            throw new runtime.RequiredError(
                'dnsZone',
                'Required parameter "dnsZone" was null or undefined when calling zoneNamePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/zone/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DnsZoneToJSON(requestParameters['dnsZone']),
        };
    }

    /**
     * Save local DNS zone file
     */
    async zoneNamePostRaw(requestParameters: ZoneNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.zoneNamePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Save local DNS zone file
     */
    async zoneNamePost(requestParameters: ZoneNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.zoneNamePostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for zoneNamePublishPost without sending the request
     */
    async zoneNamePublishPostRequestOpts(requestParameters: ZoneNamePublishPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling zoneNamePublishPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/zone/{name}/publish`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cryptographically sign and publish local zone to DHT
     */
    async zoneNamePublishPostRaw(requestParameters: ZoneNamePublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.zoneNamePublishPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cryptographically sign and publish local zone to DHT
     */
    async zoneNamePublishPost(requestParameters: ZoneNamePublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.zoneNamePublishPostRaw(requestParameters, initOverrides);
    }

}
