/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AuthorizedKid,
    AuthorizedKidFromJSON,
    AuthorizedKidToJSON,
} from '../models/AuthorizedKid';
import {
    type AuthorizedManifest,
    AuthorizedManifestFromJSON,
    AuthorizedManifestToJSON,
} from '../models/AuthorizedManifest';
import {
    type CommitRequest,
    CommitRequestFromJSON,
    CommitRequestToJSON,
} from '../models/CommitRequest';
import {
    type DeleteVdfTask200Response,
    DeleteVdfTask200ResponseFromJSON,
    DeleteVdfTask200ResponseToJSON,
} from '../models/DeleteVdfTask200Response';
import {
    type DnsZone,
    DnsZoneFromJSON,
    DnsZoneToJSON,
} from '../models/DnsZone';
import {
    type NameRenewRequest,
    NameRenewRequestFromJSON,
    NameRenewRequestToJSON,
} from '../models/NameRenewRequest';
import {
    type PublishRequest,
    PublishRequestFromJSON,
    PublishRequestToJSON,
} from '../models/PublishRequest';
import {
    type PublishResponse,
    PublishResponseFromJSON,
    PublishResponseToJSON,
} from '../models/PublishResponse';
import {
    type UpdateConfigRequest,
    UpdateConfigRequestFromJSON,
    UpdateConfigRequestToJSON,
} from '../models/UpdateConfigRequest';
import {
    type VdfRegister200Response,
    VdfRegister200ResponseFromJSON,
    VdfRegister200ResponseToJSON,
} from '../models/VdfRegister200Response';
import {
    type VdfRegisterRequest,
    VdfRegisterRequestFromJSON,
    VdfRegisterRequestToJSON,
} from '../models/VdfRegisterRequest';
import {
    type VdfTaskStatus,
    VdfTaskStatusFromJSON,
    VdfTaskStatusToJSON,
} from '../models/VdfTaskStatus';

export interface CommitNameRequest {
    commitRequest: CommitRequest;
}

export interface DeleteVdfTaskRequest {
    taskId: string;
}

export interface GetVdfStatusRequest {
    taskId: string;
}

export interface GossipPublishRequest {
    topic: string;
    body: object;
}

export interface PublishGovernanceRequest {
    body: object;
}

export interface PublishKidRequest {
    authorizedKid: AuthorizedKid;
}

export interface PublishManifestRequest {
    authorizedManifest: AuthorizedManifest;
}

export interface PublishNameRequest {
    publishRequest: PublishRequest;
}

export interface PublishZoneRequest {
    name: string;
}

export interface SaveZoneRequest {
    name: string;
    dnsZone: DnsZone;
}

export interface UpdateConfigOperationRequest {
    updateConfigRequest: UpdateConfigRequest;
}

export interface VdfRegisterOperationRequest {
    vdfRegisterRequest: VdfRegisterRequest;
}

export interface VdfRenewRequest {
    nameRenewRequest: NameRenewRequest;
}

/**
 * 
 */
export class PrivateApi extends runtime.BaseAPI {

    /**
     * Creates request options for commitName without sending the request
     */
    async commitNameRequestOpts(requestParameters: CommitNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commitRequest'] == null) {
            throw new runtime.RequiredError(
                'commitRequest',
                'Required parameter "commitRequest" was null or undefined when calling commitName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commit`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommitRequestToJSON(requestParameters['commitRequest']),
        };
    }

    /**
     * Requires Publish or Admin role.
     * Commit a name hash to DHT
     */
    async commitNameRaw(requestParameters: CommitNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.commitNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Publish or Admin role.
     * Commit a name hash to DHT
     */
    async commitName(requestParameters: CommitNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.commitNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVdfTask without sending the request
     */
    async deleteVdfTaskRequestOpts(requestParameters: DeleteVdfTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling deleteVdfTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/status/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires VDF or Admin role.
     * Delete a VDF task from memory
     */
    async deleteVdfTaskRaw(requestParameters: DeleteVdfTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteVdfTask200Response>> {
        const requestOptions = await this.deleteVdfTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVdfTask200ResponseFromJSON(jsonValue));
    }

    /**
     * Requires VDF or Admin role.
     * Delete a VDF task from memory
     */
    async deleteVdfTask(requestParameters: DeleteVdfTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteVdfTask200Response> {
        const response = await this.deleteVdfTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConfig without sending the request
     */
    async getConfigRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires Admin role.
     * Get config
     */
    async getConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getConfigRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires Admin role.
     * Get config
     */
    async getConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getConfigRaw(initOverrides);
    }

    /**
     * Creates request options for getOwnedNames without sending the request
     */
    async getOwnedNamesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/owned-names`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires Publish or Admin role.
     * Get list of locally owned names
     */
    async getOwnedNamesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getOwnedNamesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Requires Publish or Admin role.
     * Get list of locally owned names
     */
    async getOwnedNames(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getOwnedNamesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVdfStatus without sending the request
     */
    async getVdfStatusRequestOpts(requestParameters: GetVdfStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getVdfStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/status/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires VDF or Admin role.
     * Get status of a VDF task
     */
    async getVdfStatusRaw(requestParameters: GetVdfStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfTaskStatus>> {
        const requestOptions = await this.getVdfStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfTaskStatusFromJSON(jsonValue));
    }

    /**
     * Requires VDF or Admin role.
     * Get status of a VDF task
     */
    async getVdfStatus(requestParameters: GetVdfStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfTaskStatus> {
        const response = await this.getVdfStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gossipPublish without sending the request
     */
    async gossipPublishRequestOpts(requestParameters: GossipPublishRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['topic'] == null) {
            throw new runtime.RequiredError(
                'topic',
                'Required parameter "topic" was null or undefined when calling gossipPublish().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling gossipPublish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gossip/publish/{topic}`;
        urlPath = urlPath.replace('{topic}', encodeURIComponent(String(requestParameters['topic'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Requires Publish or Admin role.
     * Broadcast a payload to a Gossipsub topic
     */
    async gossipPublishRaw(requestParameters: GossipPublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.gossipPublishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Publish or Admin role.
     * Broadcast a payload to a Gossipsub topic
     */
    async gossipPublish(requestParameters: GossipPublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.gossipPublishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishGovernance without sending the request
     */
    async publishGovernanceRequestOpts(requestParameters: PublishGovernanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publishGovernance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish-governance`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Requires Governance or Admin role.
     * Publish a Governance action to DHT
     */
    async publishGovernanceRaw(requestParameters: PublishGovernanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishGovernanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Governance or Admin role.
     * Publish a Governance action to DHT
     */
    async publishGovernance(requestParameters: PublishGovernanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishGovernanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishKid without sending the request
     */
    async publishKidRequestOpts(requestParameters: PublishKidRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorizedKid'] == null) {
            throw new runtime.RequiredError(
                'authorizedKid',
                'Required parameter "authorizedKid" was null or undefined when calling publishKid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish-kid`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorizedKidToJSON(requestParameters['authorizedKid']),
        };
    }

    /**
     * Requires Publish or Admin role.
     * Publish a KID to DHT
     */
    async publishKidRaw(requestParameters: PublishKidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishKidRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Publish or Admin role.
     * Publish a KID to DHT
     */
    async publishKid(requestParameters: PublishKidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishKidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishManifest without sending the request
     */
    async publishManifestRequestOpts(requestParameters: PublishManifestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorizedManifest'] == null) {
            throw new runtime.RequiredError(
                'authorizedManifest',
                'Required parameter "authorizedManifest" was null or undefined when calling publishManifest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish-manifest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorizedManifestToJSON(requestParameters['authorizedManifest']),
        };
    }

    /**
     * Requires Publish or Admin role.
     * Publish a Capability Manifest to DHT
     */
    async publishManifestRaw(requestParameters: PublishManifestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishManifestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Publish or Admin role.
     * Publish a Capability Manifest to DHT
     */
    async publishManifest(requestParameters: PublishManifestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishManifestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishName without sending the request
     */
    async publishNameRequestOpts(requestParameters: PublishNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['publishRequest'] == null) {
            throw new runtime.RequiredError(
                'publishRequest',
                'Required parameter "publishRequest" was null or undefined when calling publishName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/publish`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PublishRequestToJSON(requestParameters['publishRequest']),
        };
    }

    /**
     * Requires Publish or Admin role.
     * Publish a name reveal to DHT
     */
    async publishNameRaw(requestParameters: PublishNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.publishNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Publish or Admin role.
     * Publish a name reveal to DHT
     */
    async publishName(requestParameters: PublishNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.publishNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishZone without sending the request
     */
    async publishZoneRequestOpts(requestParameters: PublishZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling publishZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/zone/{name}/publish`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires Publish or Admin role.
     * Cryptographically sign and publish local zone to DHT
     */
    async publishZoneRaw(requestParameters: PublishZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.publishZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires Publish or Admin role.
     * Cryptographically sign and publish local zone to DHT
     */
    async publishZone(requestParameters: PublishZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.publishZoneRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for saveZone without sending the request
     */
    async saveZoneRequestOpts(requestParameters: SaveZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling saveZone().'
            );
        }

        if (requestParameters['dnsZone'] == null) {
            throw new runtime.RequiredError(
                'dnsZone',
                'Required parameter "dnsZone" was null or undefined when calling saveZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/zone/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DnsZoneToJSON(requestParameters['dnsZone']),
        };
    }

    /**
     * Requires Publish or Admin role.
     * Save local DNS zone file
     */
    async saveZoneRaw(requestParameters: SaveZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.saveZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires Publish or Admin role.
     * Save local DNS zone file
     */
    async saveZone(requestParameters: SaveZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saveZoneRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for syncAtlas without sending the request
     */
    async syncAtlasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/atlas/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires Atlas or Admin role.
     * Trigger a synchronization of the foreign TLD bridge
     */
    async syncAtlasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishResponse>> {
        const requestOptions = await this.syncAtlasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishResponseFromJSON(jsonValue));
    }

    /**
     * Requires Atlas or Admin role.
     * Trigger a synchronization of the foreign TLD bridge
     */
    async syncAtlas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishResponse> {
        const response = await this.syncAtlasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConfig without sending the request
     */
    async updateConfigRequestOpts(requestParameters: UpdateConfigOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'updateConfigRequest',
                'Required parameter "updateConfigRequest" was null or undefined when calling updateConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateConfigRequestToJSON(requestParameters['updateConfigRequest']),
        };
    }

    /**
     * Requires Admin role.
     * Update config
     */
    async updateConfigRaw(requestParameters: UpdateConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires Admin role.
     * Update config
     */
    async updateConfig(requestParameters: UpdateConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for vdfRegister without sending the request
     */
    async vdfRegisterRequestOpts(requestParameters: VdfRegisterOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['vdfRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'vdfRegisterRequest',
                'Required parameter "vdfRegisterRequest" was null or undefined when calling vdfRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VdfRegisterRequestToJSON(requestParameters['vdfRegisterRequest']),
        };
    }

    /**
     * Requires VDF or Admin role.
     * Start VDF name registration task
     */
    async vdfRegisterRaw(requestParameters: VdfRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfRegister200Response>> {
        const requestOptions = await this.vdfRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfRegister200ResponseFromJSON(jsonValue));
    }

    /**
     * Requires VDF or Admin role.
     * Start VDF name registration task
     */
    async vdfRegister(requestParameters: VdfRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfRegister200Response> {
        const response = await this.vdfRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vdfRenew without sending the request
     */
    async vdfRenewRequestOpts(requestParameters: VdfRenewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nameRenewRequest'] == null) {
            throw new runtime.RequiredError(
                'nameRenewRequest',
                'Required parameter "nameRenewRequest" was null or undefined when calling vdfRenew().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vdf/renew`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NameRenewRequestToJSON(requestParameters['nameRenewRequest']),
        };
    }

    /**
     * Requires VDF or Admin role.
     * Start VDF name renewal task
     */
    async vdfRenewRaw(requestParameters: VdfRenewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VdfRegister200Response>> {
        const requestOptions = await this.vdfRenewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VdfRegister200ResponseFromJSON(jsonValue));
    }

    /**
     * Requires VDF or Admin role.
     * Start VDF name renewal task
     */
    async vdfRenew(requestParameters: VdfRenewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VdfRegister200Response> {
        const response = await this.vdfRenewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
