/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DnsZone,
    DnsZoneFromJSON,
    DnsZoneToJSON,
} from '../models/DnsZone';
import {
    type ResolveKid200Response,
    ResolveKid200ResponseFromJSON,
    ResolveKid200ResponseToJSON,
} from '../models/ResolveKid200Response';
import {
    type Reveal,
    RevealFromJSON,
    RevealToJSON,
} from '../models/Reveal';

export interface GetZoneRequest {
    name: string;
}

export interface GossipSubscribeRequest {
    topic: string;
}

export interface ResolveKidRequest {
    did: string;
}

export interface ResolveNameRequest {
    name: string;
}

/**
 * 
 */
export class PublicApi extends runtime.BaseAPI {

    /**
     * Creates request options for getGovernance without sending the request
     */
    async getGovernanceRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/governance`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current governance state
     */
    async getGovernanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getGovernanceRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get current governance state
     */
    async getGovernance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getGovernanceRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHealth without sending the request
     */
    async getHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get daemon health status
     */
    async getHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get daemon health status
     */
    async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkStatus without sending the request
     */
    async getNetworkStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/network-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get network status
     */
    async getNetworkStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getNetworkStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get network status
     */
    async getNetworkStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getNetworkStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPeerId without sending the request
     */
    async getPeerIdRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/peer_id`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get local peer ID
     */
    async getPeerIdRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.getPeerIdRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get local peer ID
     */
    async getPeerId(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPeerIdRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTime without sending the request
     */
    async getTimeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/time`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get verified Kinetic network time
     */
    async getTimeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getTimeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get verified Kinetic network time
     */
    async getTime(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getTimeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getZone without sending the request
     */
    async getZoneRequestOpts(requestParameters: GetZoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/zone/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get local DNS zone file
     */
    async getZoneRaw(requestParameters: GetZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DnsZone>> {
        const requestOptions = await this.getZoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DnsZoneFromJSON(jsonValue));
    }

    /**
     * Get local DNS zone file
     */
    async getZone(requestParameters: GetZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DnsZone> {
        const response = await this.getZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gossipSubscribe without sending the request
     */
    async gossipSubscribeRequestOpts(requestParameters: GossipSubscribeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['topic'] == null) {
            throw new runtime.RequiredError(
                'topic',
                'Required parameter "topic" was null or undefined when calling gossipSubscribe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gossip/subscribe/{topic}`;
        urlPath = urlPath.replace('{topic}', encodeURIComponent(String(requestParameters['topic'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subscribe to a Gossipsub topic via Server-Sent Events (SSE)
     */
    async gossipSubscribeRaw(requestParameters: GossipSubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.gossipSubscribeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Subscribe to a Gossipsub topic via Server-Sent Events (SSE)
     */
    async gossipSubscribe(requestParameters: GossipSubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.gossipSubscribeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveKid without sending the request
     */
    async resolveKidRequestOpts(requestParameters: ResolveKidRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['did'] == null) {
            throw new runtime.RequiredError(
                'did',
                'Required parameter "did" was null or undefined when calling resolveKid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/resolve-kid/{did}`;
        urlPath = urlPath.replace('{did}', encodeURIComponent(String(requestParameters['did'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve a KID
     */
    async resolveKidRaw(requestParameters: ResolveKidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveKid200Response>> {
        const requestOptions = await this.resolveKidRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResolveKid200ResponseFromJSON(jsonValue));
    }

    /**
     * Resolve a KID
     */
    async resolveKid(requestParameters: ResolveKidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveKid200Response> {
        const response = await this.resolveKidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveName without sending the request
     */
    async resolveNameRequestOpts(requestParameters: ResolveNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling resolveName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/resolve/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve a Kinetic name
     */
    async resolveNameRaw(requestParameters: ResolveNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reveal>> {
        const requestOptions = await this.resolveNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevealFromJSON(jsonValue));
    }

    /**
     * Resolve a Kinetic name
     */
    async resolveName(requestParameters: ResolveNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reveal> {
        const response = await this.resolveNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
