/* tslint:disable */
/* eslint-disable */
/**
 * Kinetic Daemon API
 * The HTTP REST API exposed by the Kinetic Daemon for domain management, VDF proofs, and resolution.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DnsZone,
    DnsZoneFromJSON,
    DnsZoneToJSON,
} from '../models/DnsZone';
import {
    type ResolveKidDidGet200Response,
    ResolveKidDidGet200ResponseFromJSON,
    ResolveKidDidGet200ResponseToJSON,
} from '../models/ResolveKidDidGet200Response';
import {
    type Reveal,
    RevealFromJSON,
    RevealToJSON,
} from '../models/Reveal';

export interface GossipSubscribeTopicGetRequest {
    topic: string;
}

export interface ResolveKidDidGetRequest {
    did: string;
}

export interface ResolveNameGetRequest {
    name: string;
}

export interface ZoneNameGetRequest {
    name: string;
}

/**
 * 
 */
export class PublicApi extends runtime.BaseAPI {

    /**
     * Creates request options for gossipSubscribeTopicGet without sending the request
     */
    async gossipSubscribeTopicGetRequestOpts(requestParameters: GossipSubscribeTopicGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['topic'] == null) {
            throw new runtime.RequiredError(
                'topic',
                'Required parameter "topic" was null or undefined when calling gossipSubscribeTopicGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gossip/subscribe/{topic}`;
        urlPath = urlPath.replace('{topic}', encodeURIComponent(String(requestParameters['topic'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subscribe to a Gossipsub topic via Server-Sent Events (SSE)
     */
    async gossipSubscribeTopicGetRaw(requestParameters: GossipSubscribeTopicGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.gossipSubscribeTopicGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Subscribe to a Gossipsub topic via Server-Sent Events (SSE)
     */
    async gossipSubscribeTopicGet(requestParameters: GossipSubscribeTopicGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.gossipSubscribeTopicGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for governanceGet without sending the request
     */
    async governanceGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/governance`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current governance state
     */
    async governanceGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.governanceGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get current governance state
     */
    async governanceGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.governanceGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthGet without sending the request
     */
    async healthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get daemon health status
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.healthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get daemon health status
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.healthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for networkStatusGet without sending the request
     */
    async networkStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/network-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get network status
     */
    async networkStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.networkStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get network status
     */
    async networkStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.networkStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for peerIdGet without sending the request
     */
    async peerIdGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/peer_id`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get local peer ID
     */
    async peerIdGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.peerIdGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get local peer ID
     */
    async peerIdGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.peerIdGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveKidDidGet without sending the request
     */
    async resolveKidDidGetRequestOpts(requestParameters: ResolveKidDidGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['did'] == null) {
            throw new runtime.RequiredError(
                'did',
                'Required parameter "did" was null or undefined when calling resolveKidDidGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/resolve-kid/{did}`;
        urlPath = urlPath.replace('{did}', encodeURIComponent(String(requestParameters['did'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve a KID
     */
    async resolveKidDidGetRaw(requestParameters: ResolveKidDidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResolveKidDidGet200Response>> {
        const requestOptions = await this.resolveKidDidGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResolveKidDidGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Resolve a KID
     */
    async resolveKidDidGet(requestParameters: ResolveKidDidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResolveKidDidGet200Response> {
        const response = await this.resolveKidDidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveNameGet without sending the request
     */
    async resolveNameGetRequestOpts(requestParameters: ResolveNameGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling resolveNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/resolve/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve a Kinetic name
     */
    async resolveNameGetRaw(requestParameters: ResolveNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reveal>> {
        const requestOptions = await this.resolveNameGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevealFromJSON(jsonValue));
    }

    /**
     * Resolve a Kinetic name
     */
    async resolveNameGet(requestParameters: ResolveNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reveal> {
        const response = await this.resolveNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for timeGet without sending the request
     */
    async timeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/time`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get verified Kinetic network time
     */
    async timeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.timeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get verified Kinetic network time
     */
    async timeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.timeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for zoneNameGet without sending the request
     */
    async zoneNameGetRequestOpts(requestParameters: ZoneNameGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling zoneNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/zone/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get local DNS zone file
     */
    async zoneNameGetRaw(requestParameters: ZoneNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DnsZone>> {
        const requestOptions = await this.zoneNameGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DnsZoneFromJSON(jsonValue));
    }

    /**
     * Get local DNS zone file
     */
    async zoneNameGet(requestParameters: ZoneNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DnsZone> {
        const response = await this.zoneNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
